name: Publish Snowstorm Client Package
on:
  release:
    types: [published]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --group test
      - name: Run tests
        run: uv run -m pytest --cov=snowstorm_client

  publish:
    name: Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --locked --all-extras
      - name: Install build dependencies
        run: uv pip install build twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          uv run -m build
          uv run -m twine check dist/*
          uv run -m twine upload dist/*
